extends:
  - '@commitlint/config-conventional'

rules:
  # Commit types
  type-enum:
    - 2
    - always
    - [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]
  type-case:
    - 2
    - always
    - lower-case
  type-empty:
    - 2
    - never

  # Scope
  scope-case:
    - 2
    - always
    - lower-case

  # Subject
  subject-case:
    - 2
    - never
    - [sentence-case, start-case, pascal-case, upper-case]
  subject-empty:
    - 2
    - never
  subject-full-stop:
    - 2
    - never
    - '.'

  # Header length
  header-max-length:
    - 2
    - always
    - 75

  # Body formatting
  body-leading-blank:
    - 1
    - always
  body-max-line-length:
    - 2
    - always
    - 150

  # Footer formatting
  footer-leading-blank:
    - 1
    - always
  footer-max-line-length:
    - 2
    - always
    - 100
